// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Data;

#nullable disable

namespace To_Do_App.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    partial class TodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("TodoApp.Models.ToDo", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Title");

                    b.ToTable("Todo");

                    b.HasData(
                        new
                        {
                            Title = "Swimming",
                            IsCompleted = true
                        },
                        new
                        {
                            Title = "Play Chess",
                            IsCompleted = false
                        },
                        new
                        {
                            Title = "Watch Movies",
                            IsCompleted = true
                        },
                        new
                        {
                            Title = "Worship",
                            IsCompleted = false
                        },
                        new
                        {
                            Title = "Lecture",
                            IsCompleted = false
                        },
                        new
                        {
                            Title = "Meal time",
                            IsCompleted = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
